/*
Created		30/08/2018
Modified		18/09/2018
Project		
Model			
Company		
Author		
Version		
Database		MS SQL 2005 
*/
create database QLBanOTo
go 
use QLBanOTo


Create table [HangXe]
(
	[ID_Hang] Integer Identity NOT NULL,
	[TenHang] Nvarchar(50) NOT NULL,
	[Logo] Text NOT NULL,
Primary Key ([ID_Hang])
) 
go

Create table [Xe]
(
	[ID_Xe] Integer Identity NOT NULL,
	[TenXe] Nvarchar(50) NOT NULL,
	[NgayDang] Datetime NOT NULL,
	[KhuVuc] Nvarchar(100) NOT NULL,
	[Anh] Text NOT NULL,
	[Gia] Float NOT NULL,
	[TenChuXe] Nvarchar(30) NOT NULL,
	[SDT] Char(12) NOT NULL,
	[DiaChi] Nvarchar(100) NOT NULL,
	[KieuDang] Nvarchar(50) NOT NULL,
	[MauSac] Nvarchar(10) NOT NULL,
	[XuatXu] Nvarchar(20) NOT NULL,
	[SoCua] Integer NOT NULL,
	[NhienLieu] Nvarchar(10) NOT NULL,
	[SoCho] Integer NOT NULL,
	[LoaiHopSo] Nvarchar(20) NOT NULL,
	[SoKm] Integer NOT NULL,
	[GioiThieu] Text NULL,
	[CongXuat] Char(50) NOT NULL,
	[MomemXoan] Char(50) NOT NULL,
	[TruyenDong] Nvarchar(30) NOT NULL,
	[DungTich] Integer NOT NULL,
	[KichThuoc_DxRxC_] Char(50) NOT NULL,
	[ChieuDaiCoSo] Float NOT NULL,
	[BanKinhQuayDau] Float NOT NULL,
	[KhoangSangGam] Float NOT NULL,
	[HeThongTreoSau] Nvarchar(100) NOT NULL,
	[TrongLuongKhongTai] Float NOT NULL,
	[Mam_Vanh] Nvarchar(50) NOT NULL,
	[KichThuocLopTruoc] Char(30) NOT NULL,
	[KichThuocLopSau] Char(30) NOT NULL,
	[PhanhTruoc] Nvarchar(10) NOT NULL,
	[PhanhSau] Nvarchar(10) NOT NULL,
	[TieuThuNhienLieu] Float NOT NULL,
	[TangAp] Nvarchar(5) NOT NULL,
	[DieuHoa] Text NULL,
	[CuaSoTroi] Text NULL,
	[DVD_LCD] Text NULL,
	[JackCamLoa] Text NULL,
	[LopSo-Cua] Text NULL,
	[TuiKhi] Text NULL,
	[Cameralui] Text NULL,
	[CamBienLui] Text NULL,
	[ChongBoCungPhanh] Text NULL,
	[PhanBoLucPhanhDienTu] Text NULL,
	[TroLucPhanhKhanCap] Text NULL,
	[HeThongHoTroKhoiDong] Text NULL,
	[NoiDangKy] Text NULL,
	[PhiTruocBa] Text NULL,
	[PhiDangKiem] Text NULL,
	[PhiDuongBo] Text NULL,
	[BaoHiemDanSu] Text NULL,
	[PhiSangTen] Text NULL,
	[TongPhi] Text NULL,
	[BanDo] Text NULL,
	[ID_Hang] Integer NOT NULL,
Primary Key ([ID_Xe])
) 
go

Create table [DonHang]
(
	[ID_DonHang] Integer Identity NOT NULL,
	[HoTen] Nvarchar(30) NOT NULL,
	[TenCongTy] Text NULL,
	[QuocGia] Text NOT NULL,
	[DiaChi] Text NOT NULL,
	[MaBuuDien] Text NULL,
	[Tinh_ThanhPho] Text NOT NULL,
	[SDT] Char(12) NOT NULL,
	[Email] Char(50) NOT NULL,
	[Note] Text NULL,
	[NgayDatHang] Datetime NOT NULL,
	[TongCong] Float NOT NULL,
	[TongPhu] Text NOT NULL,
	[HinhThucThanhToan] Text NOT NULL,
	[ID_TK] Integer NOT NULL,
	[ID_Xe] Integer NOT NULL,
Primary Key ([ID_DonHang])
) 
go

Create table [TaiKhoan]
(
	[ID_TK] Integer Identity NOT NULL,
	[HoTen] Nvarchar(30) NOT NULL,
	[Email] Char(50) NOT NULL,
	[Password] Char(30) NOT NULL,
	[SDT] Char(12) NOT NULL,
	[Tinh_ThanhPho] Nvarchar(50) NOT NULL,
	[Quan_Huyen] Nvarchar(50) NOT NULL,
	[DiaChi] Nvarchar(100) NOT NULL,
	[LoaiTK] Nvarchar(10) NOT NULL,
	[TrangThaiTK] Integer NOT NULL,
Primary Key ([ID_TK])
) 


go
SET IDENTITY_INSERT [dbo].[HangXe] ON 
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (1, N'Toyota', N'image\Logo\toyota.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (2, N'Ford', N'image\Logo\ford.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (3, N'Hyundai', N'image\Logo\hyundai.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (4, N'Honda', N'image\Logo\honda.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (5, N'KIA', N'image\Logo\kia.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (6, N'Chevrolet', N'image\Logo\Chevrolet-.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (7, N'Mazda', N'image\Logo\Mazda.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (8, N'Mitsubishi', N'image\Logo\Mitsubishi-.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (9, N'Mercedes-Benz', N'image\Logo\MercedesBenz.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (10, N'BMW', N'image\Logo\bmw.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (11, N'Nissan', N'image\Logo\Nissan-.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (12, N'Suzuki', N'image\Logo\suzuki.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (13, N'Acura', N'image\Logo\acura.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (14, N'Audi', N'image\Logo\audi.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (15, N'Bentley', N'image\Logo\Bentley-.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (16, N'Cadillac', N'image\Logo\cadilac.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (17, N'Daewoo', N'image\Logo\daewoo.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (18, N'Daihatsu', N'image\Logo\daihatsu.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (19, N'Fiat', N'image\Logo\fiat.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (20, N'Fisker', N'image\Logo\fisker.png')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (21, N'Haima', N'image\Logo\haima.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (22, N'Infiniti', N'image\Logo\Infiniti-.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (23, N'Isuzu', N'image\Logo\Isuzu-.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (24, N'Jaguar', N'image\Logo\Jaguar-.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (25, N'Land Rover', N'image\Logo\LandRover-.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (26, N'Lexus', N'image\Logo\lexus.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (27, N'MG', N'image\Logo\mg.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (28, N'Mini', N'image\Logo\MINI-.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (29, N'Peugeot', N'image\Logo\peugeot.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (30, N'Porsche', N'image\Logo\Porsche-.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (31, N'Renault', N'image\Logo\Renault-.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (32, N'SsangYong', N'image\Logo\SsangYong-.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (33, N'Subaru', N'image\Logo\subaru.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (34, N'Tata', N'image\Logo\tata.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (35, N'UAZ', N'image\Logo\uaz.png')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (36, N'Volkswagen', N'image\Logo\Volkswagen-.jpg')
INSERT [dbo].[HangXe] ([ID_Hang], [TenHang], [Logo]) VALUES (37, N'Volvo', N'image\Logo\Volvo-.jpg')
SET IDENTITY_INSERT [dbo].[HangXe] OFF
SET IDENTITY_INSERT [dbo].[Xe] ON 
/*Hang 1*/
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (1, N'2017 TOYOTA FORTUNER 2.4G', CAST(N'2018-09-14 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Toyota/Normal-2017-Toyota-Fortuner-2-4G(1).jpg;image/Toyota/Normal-2017-Toyota-Fortuner-2-4G(2).jpg;image/Toyota/Normal-2017-Toyota-Fortuner-2-4G(3).jpg;image/Toyota/Normal-2017-Toyota-Fortuner-2-4G(4).jpg;image/Toyota/Normal-2017-Toyota-Fortuner-2-4G(5).jpg;image/Toyota/Normal-2017-Toyota-Fortuner-2-4G(6).jpg;image/Toyota/Normal-2017-Toyota-Fortuner-2-4G(7).jpg;image/Toyota/Normal-2017-Toyota-Fortuner-2-4G(8).jpg;', 1035, N'PHÚ LÂM AUTO', N'0906375765  ', N'464 Kinh Dương Vương, Bình Tân, Tp Hồ Chí Minh', N'SUV/Crossover', N'Bạc', N'Nhập khẩu', 5, N'Dầu 2.4L ', 7, N'Sàn 6 cấp', 75000, N'', N'148 Hp @3,400 vòng/phút', N'400 Nm @1,600-2,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2745, 58, 219, N'Phụ thuộc, liên kết 4 điểm', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'20700000', N'340000', N'1560000', N'837400', N'150000', N'23400000', N'', 1)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (2, N'2017 TOYOTA FORTUNER 2.4G', CAST(N'2018-09-12 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Toyota/Toyota-Fortuner-2-4G-2(1).jpg;image/Toyota/Toyota-Fortuner-2-4G-2(2).jpg;image/Toyota/Toyota-Fortuner-2-4G-2(3).jpg;image/Toyota/Toyota-Fortuner-2-4G-2(4).jpg;image/Toyota/Toyota-Fortuner-2-4G-2(5).jpg;image/Toyota/Toyota-Fortuner-2-4G-2(6).jpg;image/Toyota/Toyota-Fortuner-2-4G-2(7).jpg;image/Toyota/Toyota-Fortuner-2-4G-2(8).jpg;', 1055, N'PHÚ LÂM AUTO', N'0906375765  ', N'464 Kinh Dương Vương, Bình Tân, Tp Hồ Chí Minh', N'SUV/Crossover', N'Bạc', N'Nhập khẩu', 5, N'Dầu 2.4L ', 7, N'Sàn 6 cấp', 38000, N'', N'148 Hp @3,400 vòng/phút', N'400 Nm @1,600-2,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2745, 58, 219, N'Phụ thuộc, liên kết 4 điểm', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'21100000', N'340000', N'1560000', N'837400', N'150000', N'23987400', N'', 1)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (3, N'2017 TOYOTA INNOVA 2.0E', CAST(N'2018-09-11 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Toyota/2017-Toyota-Innova-2-0E(1).jpg;image/Toyota/2017-Toyota-Innova-2-0E(2).jpg;image/Toyota/2017-Toyota-Innova-2-0E(3).jpg;image/Toyota/2017-Toyota-Innova-2-0E(4).jpg;image/Toyota/2017-Toyota-Innova-2-0E(5).jpg;image/Toyota/2017-Toyota-Innova-2-0E(6).jpg;image/Toyota/2017-Toyota-Innova-2-0E(7).jpg;image/Toyota/2017-Toyota-Innova-2-0E(8).jpg;', 718, N'PHÚ LÂM AUTO', N'0906375765  ', N'464 Kinh Dương Vương, Bình Tân, Tp Hồ Chí Minh', N'SUV/Crossover', N'Trắng', N'Trong nước', 5, N'Xăng 8.0L', 7, N'Sàn 5 cấp', 43000, N'', N'137 Hp @5,600 vòng/phút', N'183 Nm @4,000 vòng/phút', N'2WD(Cầu sau)', 70, N'4,735 x 1,830 x 1,795', 2745, 54, 178, N'Liên kết 4 điểm, lò xo cuộn và tay đòn bên', 1700, N'Hợp kim 16"', N'265/65R17', N'205/65R16', N'Đĩa', N'Tang trống', 7.8, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'14360000', N'340000', N'1560000', N'837400', N'150000', N'17247400', N'', 1)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (4, N'2016 TOYOTA FORTUNER 2.5G', CAST(N'2018-09-11 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Toyota/2016_TOYOTA_FORTUNER_2_5G(1).jpg;image/Toyota/2016_TOYOTA_FORTUNER_2_5G(2).jpg;image/Toyota/2016_TOYOTA_FORTUNER_2_5G(3).jpg;image/Toyota/2016_TOYOTA_FORTUNER_2_5G(4).jpg;image/Toyota/2016_TOYOTA_FORTUNER_2_5G(5).jpg;', 1035, N'PHÚ LÂM AUTO', N'0906375765  ', N'464 Kinh Dương Vương, Bình Tân, Tp Hồ Chí Minh', N'SUV/Crossover', N'Xám', N'Nhập khẩu', 5, N'Dầu 2.5L ', 7, N'Sàn 5 cấp', 54000, N'', N'142 Hp @3,400 vòng/phút', N'343 Nm @1,600-2,800 vòng/phút', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2750, 59, 220, N'Phụ thuộc, cơ cấu trục cố định liên kết đa điểm và thanh cân bằng', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 7.8, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'20700000', N'340000', N'1560000', N'837400', N'150000', N'23587400', N'', 1)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (5, N'2015 TOYOTA FORTUNER 2.7V 4X2', CAST(N'2018-07-17 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Toyota/2015_TOYOTA_FORTUNER_2.7V(1).jpg;image/Toyota/2015_TOYOTA_FORTUNER_2.7V(2).jpg;image/Toyota/2015_TOYOTA_FORTUNER_2.7V(3).jpg;image/Toyota/2015_TOYOTA_FORTUNER_2.7V(4).jpg;image/Toyota/2015_TOYOTA_FORTUNER_2.7V(5).jpg;image/Toyota/2015_TOYOTA_FORTUNER_2.7V(6).jpg;image/Toyota/2015_TOYOTA_FORTUNER_2.7V(7).jpg;image/Toyota/2015_TOYOTA_FORTUNER_2.7V(8).jpg;', 800, N'SALON AUTO TOÀN PHÁT', N'0903951109  ', N'C1/25 Phạm Hùng, Bình Hưng, Huyện Bình Chánh, Tp Hồ Chí Minh', N'SUV/Crossover', N'Đen', N'Trong nước', 5, N'Xăng 2.7L', 7, N'Tự động 4 cấp', 35000, N'', N'158 Hp @5,200 vòng/phút', N'241 Nm @3,800 vòng/phút', N'2WD(Cầu sau)', 80, N'4,705 x 1,840 x 1,850', 2750, 59, 220, N'Phụ thuộc, cơ cấu trục cố định liên kết đa điểm và thanh cân bằng', 1770, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'16000000', N'340000', N'1560000', N'837400', N'150000', N'18887400', N'', 1)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (6, N'2016 TOYOTA FORTUNER 2.5G', CAST(N'2018-07-17 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Toyota/2016_TOYOTA_FORTUNER_2.5G_2(1).jpg;image/Toyota/2016_TOYOTA_FORTUNER_2.5G_2(2).jpg;image/Toyota/2016_TOYOTA_FORTUNER_2.5G_2(3).jpg;image/Toyota/2016_TOYOTA_FORTUNER_2.5G_2(4).jpg;image/Toyota/2016_TOYOTA_FORTUNER_2.5G_2(5).jpg;image/Toyota/2016_TOYOTA_FORTUNER_2.5G_2(6).jpg;image/Toyota/2016_TOYOTA_FORTUNER_2.5G_2(7).jpg;image/Toyota/2016_TOYOTA_FORTUNER_2.5G_2(8).jpg;', 905, N'SALON AUTO TOÀN PHÁT', N' 0903951109 ', N'C1/25 Phạm Hùng, Bình Hưng, Huyện Bình Chánh, Tp Hồ Chí Minh', N'SUV/Crossover', N'Bạc', N'Trong nước', 5, N'Dầu 2.4L ', 7, N'Sàn 5 cấp', 32000, N'', N'142 Hp @3,400 vòng/phút', N'343 Nm @1,600-2,800 vòng/phút', N'2WD(Cầu sau)', 80, N'4,705 x 1,840 x 1,850', 2750, 59, 220, N'Phụ thuộc, cơ cấu trục cố định liên kết đa điểm và thanh cân bằng', 1820, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'18100000', N'340000', N'1560000', N'837400', N'150000', N'20987400', N'', 1)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (7, N'2015 TOYOTA COROLLA ALTIS 1.8G CVT', CAST(N'2018-09-19 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Toyota/2015_TOYOTA_COROLLA_ALTIS_1.8G_CVT(1).jpg;image/Toyota/2015_TOYOTA_COROLLA_ALTIS_1.8G_CVT(2).jpg;image/Toyota/2015_TOYOTA_COROLLA_ALTIS_1.8G_CVT(3).jpg;image/Toyota/2015_TOYOTA_COROLLA_ALTIS_1.8G_CVT(4).jpg;image/Toyota/2015_TOYOTA_COROLLA_ALTIS_1.8G_CVT(5).jpg;image/Toyota/2015_TOYOTA_COROLLA_ALTIS_1.8G_CVT(6).jpg;', 662, N'WESTERN FORD', N'0902295938  ', N'530 Kinh dương Vương, An Lạc, Bình Tân, Tp Hồ Chí Minh', N'Sedan', N'Nâu', N'Trong nước', 4, N'Xăng 1.8L', 5, N'Tự động Vô cấp', 25000, N'', N'138 Hp @6,400 vòng/phút', N'173 Nm @4,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,620 x 1,775 x 1,460', 2700, 54, 130, N'Bán độc lập, cơ cấu dầm xoắn (torsion beam) và thanh cân bằng', 1260, N'Hợp kim 16"', N'205/55R16 ', N'265/65R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'13,240000', N'340000', N'1560000', N'837400', N'150000', N'16726700', N'', 1)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (8, N'2016 TOYOTA COROLLA ALTIS 1.8G CVT', CAST(N'2018-09-08 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Toyota/2016_TOYOTA_COROLLA_ALTIS_1.8G_CVT(1).jpg;image/Toyota/2016_TOYOTA_COROLLA_ALTIS_1.8G_CVT(2).jpg;image/Toyota/2016_TOYOTA_COROLLA_ALTIS_1.8G_CVT(3).jpg;image/Toyota/2016_TOYOTA_COROLLA_ALTIS_1.8G_CVT(4).jpg;image/Toyota/2016_TOYOTA_COROLLA_ALTIS_1.8G_CVT(5).jpg;image/Toyota/2016_TOYOTA_COROLLA_ALTIS_1.8G_CVT(6).jpg;', 625, N'Mr Thọ - Western Ford', N'0937470911  ', N'530 Kinh Dương Vương, Bình Tân, Tp Hồ Chí Minh', N'Sedan', N'Bạc', N'Trong nước', 5, N'Dầu 2.4L ', 7, N'Sàn 6 cấp', 75000, N'', N'148 Hp @3,400 vòng/phút', N'400 Nm @1,600-2,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2745, 58, 219, N'Phụ thuộc, liên kết 4 điểm', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'12500000', N'340000', N'1560000', N'837400', N'150000', N'15986700', N'', 1)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (9, N'2015 TOYOTA FORTUNER 2.7V 4X4', CAST(N'2018-09-14 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Toyota/9/9(1).jpg;image/Toyota/9/9(2).jpg;image/Toyota/9/9(3).jpg;image/Toyota/9/9(4).jpg;image/Toyota/9/9(5).jpg;image/Toyota/9/9(6).jpg;', 822, N'Ô TÔ CŨ', N'0915511513  ', N'550 kinh dương vương, Bình Tân, Tp Hồ Chí Minh', N'SUV/Crossover', N'Đen', N'Trong nước', 4, N'Xăng 2.7L', 7, N'Tự động 4 cấp', 67000, N'', N'158 Hp @5,200 vòng/phút', N'241 Nm @3,800 vòng/phút', N'2WD(Cầu sau)', 80, N'4,705 x 1,840 x 1,850', 2750, 59, 220, N'Phụ thuộc, cơ cấu trục cố định liên kết đa điểm và thanh cân bằng', 1770, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'12500000', N'340000', N'1560000', N'837400', N'150000', N'15986700', N'', 1)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (10, N'2015 TOYOTA INNOVA G', CAST(N'2018-09-19 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Toyota/2015-Toyota-Innova-G(1).jpg;image/Toyota/2015-Toyota-Innova-G(1).jpg;image/Toyota/2015-Toyota-Innova-G(1).jpg;image/Toyota/2015-Toyota-Innova-G(4).jpg;image/Toyota/2015-Toyota-Innova-G(5).jpg;image/Toyota/2015-Toyota-Innova-G(6).jpg;image/Toyota/2015-Toyota-Innova-G(7).jpg;', 670, N'Nguyễn Trung', N'0937898381  ', N'63A Nguyễn Văn Lượng, Phường 10, Quận Gò Vấp, Gò Vấp, Tp Hồ Chí Minh', N'Wagon/Van/ Minivan/MPV', N'Bạc', N'Trong nước', 5, N'Xăng 2.0L', 8, N'Tự động 4 cấp', 37000, N'', N'134 Hp @5,600 vòng/phút', N'182 Nm @4,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,589 x 1,775 x 1,750', 2750, 54, 176, N'Phụ thuộc, cơ cấu trục cố định liên kết đa điểm và thanh cân bằng', 1605, N'Hợp kim 15"', N'205/65R15', N'205/65R15', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'13400000', N'340000', N'1560000', N'837400', N'150000', N'16287400', N'', 1)
/*Hang 2*/
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (11, N'2015 FORD RANGER XLS 2.2 4X2 MT', CAST(N'2018-07-29 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Ford/2015-Ford-Ranger-XLS(1).jpg;image/Ford/2015-Ford-Ranger-XLS(2).jpg;image/Ford/2015-Ford-Ranger-XLS(3).jpg;image/Ford/2015-Ford-Ranger-XLS(4).jpg;image/Ford/2015-Ford-Ranger-XLS(5).jpg;image/Ford/2015-Ford-Ranger-XLS(6).jpg;', 535, N'SALON AUTO TOÀN PHÁT', N'0903951109  ', N'C1/25 Phạm Hùng, Bình Hưng, Huyện Bình Chánh, Tp Hồ Chí Minh', N'Pickup', N'Bạc', N'Nhập khẩu', 4, N'Dầu 2.2L', 5, N'àn 6 cấp', 46000, N'', N'123 Hp @3,700 vòng/phút', N'320 Nm @1,600-1,700 vòng/phút', N'2WD(Cầu sau)', 80, N'5,362 x 1,860 x 1,815', 3220, 64, 200, N'Nhíp với ống giảm chấn', 1929, N'Hợp kim 16''''', N'255/70R16', N'255/70R16', N'Đĩa', N'Tang trống', 6.2, N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'10700000', N'340000', N'1560000', N'8026300', N'150000', N'19372300', N'', 2)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (12, N'2005 FORD EVEREST DIESEL XLT 4X4', CAST(N'2018-07-29 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Ford/2005-Ford-Everest-Diesel-XLT-4x4(1).jpg;image/Ford/2005-Ford-Everest-Diesel-XLT-4x4(2).jpg;image/Ford/2005-Ford-Everest-Diesel-XLT-4x4(3).jpg;image/Ford/2005-Ford-Everest-Diesel-XLT-4x4(4).jpg;image/Ford/2005-Ford-Everest-Diesel-XLT-4x4(5).jpg;image/Ford/2005-Ford-Everest-Diesel-XLT-4x4(6).jpg;image/Ford/2005-Ford-Everest-Diesel-XLT-4x4(7).jpg;', 535, N'SALON AUTO TOÀN PHÁT', N'0938595373', N'C1/25 Phạm Hùng, Bình Hưng, Huyện Bình Chánh, Tp Hồ Chí Minh', N'SUV/Crossover', N'Bạc', N'Trong nước', 5, N'Xăng 2.5L', 7, N'Sàn 6 cấp', 78000, N'', N'148 Hp @3,400 vòng/phút', N'400 Nm @1,600-2,000 vòng/phút ', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2745, 58, 219, N'Phụ thuộc, liên kết 4 điểm', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'10700000', N'340000', N'1560000', N'837400', N'150000', N'13587400', N'', 2)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (13, N'2016 FORD RANGER WILDTRAK 3.2 4X4 AT', CAST(N'2018-05-02 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Ford/2016-Ford-Ranger-WILDTRAK-3-2-4X4(1).jpg;image/Ford/2016-Ford-Ranger-WILDTRAK-3-2-4X4(2).jpg;image/Ford/2016-Ford-Ranger-WILDTRAK-3-2-4X4(3).jpg;image/Ford/2016-Ford-Ranger-WILDTRAK-3-2-4X4(4).jpg;image/Ford/2016-Ford-Ranger-WILDTRAK-3-2-4X4(5).jpg;image/Ford/2016-Ford-Ranger-WILDTRAK-3-2-4X4(6).jpg;image/Ford/2016-Ford-Ranger-WILDTRAK-3-2-4X4(7).jpg;image/Ford/2016-Ford-Ranger-WILDTRAK-3-2-4X4(8).jpg;', 850, N'SALON AUTO TOÀN PHÁT', N'0903951109  ', N'C1/25 Phạm Hùng, Bình Hưng, Huyện Bình Chánh, Tp Hồ Chí Minh', N'Pickup', N'Cam', N'Nhập khẩu', 5, N'Dầu 3.2L', 5, N'Tự động 6 cấp', 32000, N'', N'148 Hp @3,400 vòng/phút', N'400 Nm @1,600-2,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2745, 58, 219, N'Phụ thuộc, liên kết 4 điểm', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'17000000', N'340000', N'1560000', N'837400', N'150000', N'25672300', N'', 2)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (14, N'2017 FORD RANGER XLS 2.2 4X2 MT', CAST(N'2018-09-14 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Ford/2017-Ford-Ranger-XLS-2-2-4x2-MT(1).jpg;image/Ford/2017-Ford-Ranger-XLS-2-2-4x2-MT(2).jpg;image/Ford/2017-Ford-Ranger-XLS-2-2-4x2-MT(3).jpg;image/Ford/2017-Ford-Ranger-XLS-2-2-4x2-MT(4).jpg;image/Ford/2017-Ford-Ranger-XLS-2-2-4x2-MT(5).jpg;image/Ford/2017-Ford-Ranger-XLS-2-2-4x2-MT(6).jpg;', 615, N'WESTERN FORD', N'0902295938  ', N'530 Kinh dương Vương, An Lạc, Bình Tân, Tp Hồ Chí Minh', N'Pickup', N'Xanh dương', N'Nhập khẩu', 4, N'Dầu 2.2L ', 7, N'Sàn 6 cấp', 25000, N'', N'148 Hp @3,400 vòng/phút', N'400 Nm @1,600-2,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2745, 58, 219, N'Phụ thuộc, liên kết 4 điểm', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'12300000', N'340000', N'1560000', N'837400', N'150000', N'20972300', N'', 2)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (15, N'2014 FORD TRANSIT 2.4', CAST(N'2018-09-14 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Ford/2014-Ford-Transit-2-4(1).jpg;image/Ford/2014-Ford-Transit-2-4(2).jpg;image/Ford/2014-Ford-Transit-2-4(3).jpg;image/Ford/2014-Ford-Transit-2-4(4).jpg;image/Ford/2014-Ford-Transit-2-4(5).jpg;image/Ford/2014-Ford-Transit-2-4(6).jpg;image/Ford/2014-Ford-Transit-2-4(7).jpg;image/Ford/2014-Ford-Transit-2-4(8).jpg;', 549, N'Đào Việt Bình', N'0908404086  ', N'530 Kinh Dương Vương, Bình Tân, Tp Hồ Chí Minh', N'Wagon/Van/ Minivan/MPV', N'Bạc', N'Trong nước', 4, N'Xăng 2.4L', 16, N'Sàn 4 cấp', 98000, N'', N'148 Hp @3,400 vòng/phút', N'400 Nm @1,600-2,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2745, 58, 219, N'Phụ thuộc, liên kết 4 điểm', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'10980000', N'340000', N'1560000', N'837400', N'150000', N'14427000', N'', 2)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (16, N'2009 FORD EVEREST LIMITED 4X2', CAST(N'2018-09-14 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Ford/2009-Ford-Everest-Limited-4x2(1).jpg;image/Ford/2009-Ford-Everest-Limited-4x2(2).jpg;image/Ford/2009-Ford-Everest-Limited-4x2(3).jpg;image/Ford/2009-Ford-Everest-Limited-4x2(4).jpg;image/Ford/2009-Ford-Everest-Limited-4x2(5).jpg;image/Ford/2009-Ford-Everest-Limited-4x2(6).jpg;image/Ford/2009-Ford-Everest-Limited-4x2(7).jpg;image/Ford/2009-Ford-Everest-Limited-4x2(8).jpg;', 510, N'Đào Việt Bình', N'0908404086  ', N'530 Kinh Dương Vương, Bình Tân, Tp Hồ Chí Minh', N'SUV/Crossover', N'Hồng', N'Trong nước', 5, N'Xăng 2.5L', 7, N'Tự động 4 cấp', 86000, N'', N'148 Hp @3,400 vòng/phút', N'400 Nm @1,600-2,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2745, 58, 219, N'Phụ thuộc, liên kết 4 điểm', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'10200000', N'340000', N'1560000', N'837400', N'150000', N'13087400', N'', 2)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (17, N'2014 FORD ECOSPORT MT TREND 1.5L', CAST(N'2018-09-14 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Ford/2014-Ford-Ecosport-MT-Trend-1-5L(1).jpg;image/Ford/2014-Ford-Ecosport-MT-Trend-1-5L(2).jpg;image/Ford/2014-Ford-Ecosport-MT-Trend-1-5L(3).jpg;image/Ford/2014-Ford-Ecosport-MT-Trend-1-5L(4).jpg;image/Ford/2014-Ford-Ecosport-MT-Trend-1-5L(5).jpg;image/Ford/2014-Ford-Ecosport-MT-Trend-1-5L(6).jpg;', 435, N'Ô TÔ CŨ', N'0915511513  ', N'550 kinh dương vương, Bình Tân, Tp Hồ Chí Minh ', N'SUV/Crossover', N'Nâu', N'Trong nước', 5, N'Xăng 1.5L', 5, N'Sàn 5 cấp', 79000, N'', N'148 Hp @3,400 vòng/phút', N'400 Nm @1,600-2,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2745, 58, 219, N'Phụ thuộc, liên kết 4 điểm', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'8700000', N'340000', N'1560000', N'837400', N'150000', N'12186700', N'', 2)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (18, N'2013 FORD EVEREST 4X2 AT LIMITED', CAST(N'2018-09-20 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Ford/2013-Ford-Everest-4x2-AT-Limited(1).jpg;image/Ford/2013-Ford-Everest-4x2-AT-Limited(2).jpg;image/Ford/2013-Ford-Everest-4x2-AT-Limited(3).jpg;image/Ford/2013-Ford-Everest-4x2-AT-Limited(4).jpg;image/Ford/2013-Ford-Everest-4x2-AT-Limited(5).jpg;image/Ford/2013-Ford-Everest-4x2-AT-Limited(6).jpg;', 628, N'Ô TÔ CŨ', N'0915511513  ', N'550 kinh dương vương, Bình Tân, Tp Hồ Chí Minh ', N'SUV/Crossover', N'Trắng', N'Nhập khẩu', 5, N'Dầu 2.5L', 7, N'Tự động 5 cấp', 83000, N'', N'148 Hp @3,400 vòng/phút', N'400 Nm @1,600-2,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2745, 58, 219, N'Phụ thuộc, liên kết 4 điểm', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'12560000', N'340000', N'1560000', N'837400', N'150000', N'15447400', N'', 2)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (19, N'2009 FORD RANGER XLT 2.5 TDCI MT 4X4', CAST(N'2018-09-14 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Ford/2009-Ford-Ranger-XLT-2-5-TDCi-MT-4X4(1).jpg;image/Ford/2009-Ford-Ranger-XLT-2-5-TDCi-MT-4X4(2).jpg;image/Ford/2009-Ford-Ranger-XLT-2-5-TDCi-MT-4X4(3).jpg;image/Ford/2009-Ford-Ranger-XLT-2-5-TDCi-MT-4X4(4).jpg;image/Ford/2009-Ford-Ranger-XLT-2-5-TDCi-MT-4X4(5).jpg;image/Ford/2009-Ford-Ranger-XLT-2-5-TDCi-MT-4X4(6).jpg;image/Ford/2009-Ford-Ranger-XLT-2-5-TDCi-MT-4X4(7).jpg;', 408, N'Ô TÔ CŨ', N'0915511513  ', N'550 kinh dương vương, Bình Tân, Tp Hồ Chí Minh ', N'Pickup', N'Xanh dương', N'Nhập khẩu', 4, N'Dầu 2.5L', 5, N'Sàn 5 cấp', 100000, N'', N'148 Hp @3,400 vòng/phút', N'400 Nm @1,600-2,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2745, 58, 219, N'Phụ thuộc, liên kết 4 điểm', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'8160000', N'340000', N'1560000', N'837400', N'150000', N'16832300', N'', 2)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (20, N'2016 FORD TRANSIT 2.4 - 16 CHỖ TIÊU CHUẨN', CAST(N'2018-09-18 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Ford/2016-Ford-Transit-2-4(1).jpg;image/Ford/2016-Ford-Transit-2-4(2).jpg;image/Ford/2016-Ford-Transit-2-4(3).jpg;image/Ford/2016-Ford-Transit-2-4(4).jpg;image/Ford/2016-Ford-Transit-2-4(5).jpg;image/Ford/2016-Ford-Transit-2-4(6).jpg;image/Ford/2016-Ford-Transit-2-4(7).jpg;image/Ford/2016-Ford-Transit-2-4(8).jpg;', 645, N'Mr Thọ - Western Ford', N'0937470911  ', N'530 Kinh Dương Vương, Bình Tân, Tp Hồ Chí Minh', N'Wagon/Van/ Minivan/MPV', N'Đen/Xám', N'Trong nước', 4, N'Xăng 2.4L', 16, N'Sàn 4 cấp', 82000, N'', N'134 Hp @5,600 vòng/phút', N'182 Nm @4,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,589 x 1,775 x 1,750 ', 2.75, 54, 176, N'Phụ thuộc, cơ cấu trục cố định liên kết đa điểm và thanh cân bằng', 1.605, N'Hợp kim 15"', N'205/65R15', N'205/65R15', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'12900000', N'340000', N'1560000', N'837400', N'150000', N'16347000', N'', 2)
/*Hang 5*/
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (41, N'2017 KiaRondo GATH', CAST(N'2018-09-12 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Kia/kia1.jpg;image/Kia/kia2.jpg;image/Kia/kia3.jpg;image/Kia/kia4.jpg;image/Kia/kia5.jpg;image/Kia/kia6.jpg;image/Kia/kia7.jpg;image/Kia/kia8.jpg;',620, N'PHÚ LÂM AUTO', N' 01639503339 ', N'464 Kinh Dương Vương, Bình Tân, Tp Hồ Chí Minh', N'Wagon/Van/ Minivan/MPV', N'Vàng', N'Nhập khẩu', 5, N'Xăng 2.0L ', 7, N'Tự động 6 cấp', 16000, N'', N'159 Hp@6,500 vòng/phút', N'194 Nm@4,800 vòng/phút', N'2WD(Cầu trước)', 58, N'4,525 x 1,805 x 1,610', 2745, 2.2, 151, N'Thanh xoắn',1510, N'Hợp kim nhôm', N'225/45R17', N'2225/45R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'20700', N'340000', N'15600', N'837400', N'150000', N'23400', N'k',5)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (42, N'2016 KIA CERATO 1.6 MT', CAST(N'2018-09-14 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Kia/kiacer1.jpg;image/Kia/kiacer1.jpg;image/Kia/kiacer2.jpg;image/Kia/kiacer2.jpg;image/Kia/kiacer6.jpg;image/Kia/kiacer3.jpg;image/Kia/kiacer4.jpg;image/Kia/kiacer5.jpg;', 303, N'SALON AUTO TOÀN PHÁT', N' 0906375765 ', N'464 Kinh Dương Vương, Bình Tân, Tp Hồ Chí Minh', N'Sedar', N'Trắng', N'Trong nước', 4, N'Xăng 1.6L ', 5, N'Sàn 6 cấp', 26000, N'', N'128 Hp @6,300 vòng/phút', N'157 Nm @4,850 vòng/phút', N'2WD(Cầu trước)', 80, N'4,560 x 1,780 x 1,445', 2700, 5.3, 219, N'Độc lập, cơ cấu thanh chống MacPherson và thanh cân bằng',1290, N'Hợp kim 16"', N'265/65R17', N'265/65R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'5000000', N'340000', N'15600', N'837400', N'150000', N'1000000', N'k',5)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (43, N'2013 KIA RIO 1.4 AT HATCHBACK', CAST(N'2018-09-14 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Kia/kiario1.jpg;image/Kia/kiario1.jpg;image/Kia/kiario1.jpg;image/Kia/kiario2.jpg;image/Kia/kiario3.jpg;image/Kia/kiario4.jpg;image/Kia/kiario5.jpg;image/Kia/kiario6.jpg;', 435, N'Kim Yến', N'  0962502549 ', N'KD. Vsip, bình hoà, Thị xã Thuận An, Bình Dương', N'Hatchback', N'p', N'Nhập khẩu', 5, N'Xăng 1.6L ', 5, N'Tự động 6 cấp', 20000, N'', N'128 Hp @6,300 vòng/phút', N'157 Nm @4,850 vòng/phút', N'2WD(Cầu trước)', 80, N'4,560 x 1,780 x 1,445', 2700, 5.3, 219, N'Độc lập, cơ cấu thanh chống MacPherson và thanh cân bằng',1060, N'Hợp kim 16"', N'265/65R17', N'265/65R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'6000000', N'340000', N'15600', N'837400', N'150000', N'15000000', N'k',5)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (44, N'2011 KIA MORNING 1.0 AT', CAST(N'2018-08-14 00:00:00.000' AS DateTime), N'Tp Hà Nội', N'image/Kia/kiamor1.jpg;image/Kia/kiamor2.jpg;image/Kia/kiamor1.jpg;image/Kia/kiamor3.jpg;image/Kia/kiamor4.jpg;image/Kia/kiamor5.jpg;image/Kia/kiamor6.jpg;image/Kia/kiamor1.jpg;', 335, N'Tuấn Anh', N'01679704391', N'Quận Đống Đa , Tp Hà Nội', N'Hatchback', N'Trắng', N'Nhập khẩu', 5, N'Xăng 6.0L ', 5, N'Tự động 5 cấp', 55000, N'', N'128 Hp @6,300 vòng/phút', N'157 Nm @4,850 vòng/phút', N'2WD(Cầu sau)', 60, N'4,560 x 1,780 x 1,445', 2700, 5.3, 219, N'Trục xoắn lò xo trụ',1290, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'20700', N'340000', N'15600', N'837400', N'150000', N'23400', N'k',5)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (45, N'2010 KIA CARENS SX 2.0 MT', CAST(N'2018-09-10 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Kia/kiacar1.jpg;image/Kia/kiacar1.jpg;image/Kia/kiacar4.jpg;image/Kia/kiacar2.jpg;image/Kia/kiacar1.jpg;image/Kia/kiacar3.jpg;image/Kia/kiacar4.jpg;image/Kia/kiacar5.jpg;', 335, N'Anh Nam', N' 0906757575 ', N'246a Nguyễn Ánh Thủ,Hiệp Thành,q12, Quận 12, Tp Hồ Chí Minh', N'Sedar', N'Xám', N'Nhập khẩu', 5, N'Xăng 2.0L ', 7, N'Sàn 5 cấp', 76000, N'', N'143 Hp @6,000 vòng/phút', N'188 Nm @4,250 vòng/phút', N'2WD(Cầu trước)', 65, N'4,545 x 1,820 x 1,720', 2700, 5.3, 156, N'Độc lập, cơ cấu liên kết đa điểm (multi-link) và thanh cân bằng',1290, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'7000000', N'340000', N'15600', N'837400', N'150000', N'20000000', N'k',5)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (46, N'2015 KIA GRAND SEDONA GAT', CAST(N'2018-08-14 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Kia/kiagran1.jpg;image/Kia/kiagran2.jpg;image/Kia/kiagran3.jpg;image/Kia/kiagran4.jpg;image/Kia/kiagran5.jpg;image/Kia/kiagran6.jpg;image/Kia/kiagran1.jpg;image/Kia/kiagran2.jpg;', 999, N'Nguyễn Duy Cường', N'0909998508', N'Lũy Bán Bích, Q.Tân Phú, Tp Hồ Chí Minh', N' Wagon/Van/ Minivan/MPV', N'Trắng', N'Nhập', 5, N'Xăng 3.3L ', 7, N'Sàn 6 cấp', 40000, N'', N'266 Hp @6,400 vòng/phút', N'318 Nm @5,200 vòng/phút', N'2WD(Cầu trước)', 80, N'5,115 x 1,985 x 1,755', 3060, 5.7, 163, N'Đa liên kết',2020, N'Hợp kim 16"', N'265/65R17', N'265/65R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'4000000', N'340000', N'15600', N'837400', N'150000', N'23400', N'k',5)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (47, N'2015 KIA SORENTO 2.4G AT 4X2', CAST(N'2018-09-14 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Kia/kiasor1.jpg;image/Kia/kiasor2.jpg;image/Kia/kiasor1.jpg;image/Kia/kiasor2.jpg;image/Kia/kiasor3.jpg;image/Kia/kiasor4.jpg;image/Kia/kiasor1.jpg;image/Kia/kiasor5.jpg;', 745, N'Phát Hoàng', N'0902326839 ', N'Gò Vấp, Tp Hồ Chí Minh', N'SUV/Crossover', N'Đen', N'Nhập khẩu', 5, N'Xăng 2.4L ', 7, N'Tự động 6 cấp', 20000, N'', N'172 Hp @6,300 vòng/phút', N'227 Nm @4,850 vòng/phút', N'2WD(Cầu trước)', 80, N'4,560 x 1,780 x 1,445', 2700, 5.3, 219, N'Độc lập, cơ cấu thanh chống MacPherson và thanh cân bằng',1790, N'Hợp kim 16"', N'265/65R17', N'265/65R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'12000000', N'340000', N'15600', N'837400', N'150000', N'23400000', N'k',5)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (48, N'2016 KIA SEDONA 2.2L', CAST(N'2018-09-14 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Kia/kiased1.jpg;image/Kia/kiased2.jpg;image/Kia/kiased3.jpg;image/Kia/kiased4.jpg;image/Kia/kiased1.jpg;image/Kia/kiased2.jpg;image/Kia/kiased3.jpg;image/Kia/kiased4.jpg;', 1015, N'SALON AUTO TOÀN PHÁT', N' 0906375765 ', N'550 Kinh Dương Vương, Bình Tân, Tp Hồ Chí Minh', N'Sedanr', N'p', N'Trong nước', 4, N'Xăng 1.6L ', 5, N'Sàn 6 cấp', 26000, N'', N'128 Hp @6,300 vòng/phút', N'157 Nm @4,850 vòng/phút', N'2WD(Cầu trước)', 80, N'4,560 x 1,780 x 1,445', 2700, 5.3, 219, N'Độc lập, cơ cấu thanh chống MacPherson và thanh cân bằng',1290, N'Hợp kim 16"', N'265/65R17', N'265/65R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'20700', N'340000', N'15600', N'837400', N'150000', N'23400', N'k',5)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (49, N'2015 KIA SORENTO 2.2AT CRDI', CAST(N'2018-09-14 00:00:00.000' AS DateTime), N'Tp Hà Nội', N'image/Kia/kia1.jpg;image/Kia/kia2.jpg;image/Kia/kia3.jpg;image/Kia/kia4.jpg;image/Kia/kia5.jpg;image/Kia/kia6.jpg;image/Kia/kia7.jpg;image/Kia/kia8.jpg;', 976, N'Anycar Hà Nội', N' 0906375765 ', N'Quận Nam Từ Liêm, Tp Hà Nội', N'SUV/Crossover', N'p', N'Trong nước', 4, N'Xăng 1.6L ', 5, N'Sàn 6 cấp', 26000, N'', N'128 Hp @6,300 vòng/phút', N'157 Nm @4,850 vòng/phút', N'2WD(Cầu trước)', 80, N'4,560 x 1,780 x 1,445', 2700, 5.3, 219, N'Độc lập, cơ cấu thanh chống MacPherson và thanh cân bằng',2290, N'Hợp kim 16"', N'265/65R17', N'265/65R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'19480000', N'340000', N'15600', N'837400', N'150000', N'22367400', N'k',5)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (50, N'2016 KIA CERATO 1.6 MT', CAST(N'2018-09-14 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Kia/kiario1.jpg;image/Kia/kiario1.jpg;image/Kia/kiario1.jpg;image/Kia/kiario2.jpg;image/Kia/kiario3.jpg;image/Kia/kiario4.jpg;image/Kia/kiario5.jpg;image/Kia/kiario6.jpg;', 335, N'SALON AUTO TOÀN PHÁT', N' 0906375765 ', N'464 Kinh Dương Vương, Bình Tân, Tp Hồ Chí Minh', N'Sedanr', N'p', N'Trong nước', 4, N'Xăng 1.6L ', 5, N'Sàn 6 cấp', 26000, N'', N'128 Hp @6,300 vòng/phút', N'157 Nm @4,850 vòng/phút', N'2WD(Cầu trước)', 80, N'4,560 x 1,780 x 1,445', 2700, 5.3, 219, N'Độc lập, cơ cấu thanh chống MacPherson và thanh cân bằng',1290, N'Hợp kim 16"', N'265/65R17', N'265/65R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'1000000', N'340000', N'15600', N'837400', N'150000', N'2000000', N'k',5)

/*Hang 6*/
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (51, N'2015 CHEVROLET CAPTIVA LTZ 2.4', CAST(N'2018-09-12 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Chevrolet/chev1.jpg;image/Chevrolet/chev2.jpg;image/Chevrolet/chev3.jpg;image/Chevrolet/chev4.jpg;image/Chevrolet/chev1.jpg;image/Chevrolet/chev2.jpg;image/Chevrolet/chev3.jpg;image/Chevrolet/chev4.jpg;',620, N'PHÚ LÂM AUTO', N' 01639503339 ', N'464 Kinh Dương Vương, Bình Tân, Tp Hồ Chí Minh', N'Wagon/Van/ Minivan/MPV', N'Xám', N'Nhập khẩu', 5, N'Xăng 2.0L ', 7, N'Tự động 6 cấp', 16000, N'', N'159 Hp@6,500 vòng/phút', N'194 Nm@4,800 vòng/phút', N'2WD(Cầu trước)', 58, N'4,525 x 1,805 x 1,610', 2745, 2.2, 151, N'Bán độc lập, cơ cấu dầm xoắn (torsion beam) và thanh cân bằng',1510, N'Hợp kim nhôm', N'225/45R17', N'2225/45R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'9000000', N'340000', N'15600', N'837400', N'150000', N'12486700', N'k',6)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (52, N'2016 CHEVROLET CRUZE LT', CAST(N'2018-09-12 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Chevrolet/chev5.jpg;image/Chevrolet/chev6.jpg;image/Chevrolet/chev7.jpg;image/Chevrolet/chev8.jpg;image/Chevrolet/chev5.jpg;image/Chevrolet/chev6.jpg;image/Chevrolet/chev7.jpg;image/Chevrolet/chev8.jpg;',450, N'SALON AUTO TOÀN PHÁT', N' 0938595373 ', N'C1/25 Phạm Hùng, Bình Hưng, Huyện Bình Chánh, Tp Hồ Chí Minh', N'Sedan', N'Trắng', N'Nhập khẩu', 4, N'Xăng 2.0L ', 5, N'Tự động 6 cấp', 30000, N'', N'159 Hp@6,500 vòng/phút', N'194 Nm@4,800 vòng/phút', N'2WD(Cầu trước)', 58, N'4,597 x 1,788 x 1,477', 2658, 5.4, 160, N'Thanh xoắn',1285, N'Hợp kim nhôm', N'225/45R17', N'2225/45R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'9000000', N'340000', N'15600', N'837400', N'150000', N'12486700', N'k',6)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (53, N'2015 CHEVROLET SPARK LTZ 1.0', CAST(N'2018-09-12 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Chevrolet/chev9.jpg;image/Chevrolet/chev10.jpg;image/Chevrolet/chev11.jpg;image/Chevrolet/chev12.jpg;image/Chevrolet/chev9.jpg;image/Chevrolet/chev10.jpg;image/Chevrolet/chev11.jpg;image/Chevrolet/chev12.jpg;',315, N'SALON AUTO TOÀN PHÁT', N' 01639503339 ', N'C1/25 Phạm Hùng, Bình Hưng, Huyện Bình Chánh, Tp Hồ Chí Minh', N'Hatchback', N'Trắng', N'Trong nước', 5, N'Xăng 2.0L ', 7, N'Tự động 4 cấp',30000, N'', N'159 Hp@6,500 vòng/phút', N'194 Nm@4,800 vòng/phút', N'2WD(Cầu trước)', 58, N'4,525 x 1,805 x 1,610', 2745, 2.2, 151, N'Thanh xoắn',1510, N'Hợp kim 14"', N'225/45R17', N'2225/45R17', N'Đĩa', N'Không', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'6300000', N'340000', N'15600', N'837400', N'150000', N'9786700', N'k',6)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (54, N'2016 CHEVROLET ORLANDO LTZ 1.8', CAST(N'2018-09-12 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Chevrolet/chev13.jpg;image/Chevrolet/chev14.jpg;image/Chevrolet/chev15.jpg;image/Chevrolet/chev16.jpg;image/Chevrolet/chev13.jpg;image/Chevrolet/chev14.jpg;image/Chevrolet/chev15.jpg;image/Chevrolet/chev16.jpg;',565, N'Kim Anh', N'0911936868', N'Gò Vấp, Tp Hồ Chí Minh', N'Wagon/Van/ Minivan/MPV', N'Bạc', N'Trong nước', 5, N'Xăng 1.8L ', 7, N'Tự động 6 cấp', 16000, N'', N'161 Hp @3,600 vòng/phút', N'176 Nm @3,800 vòng/phút', N'2WD(Cầu trước)', 58, N'4,652 x 1,836 x 1,633', 2745, 5.6, 151, N'Bán độc lập, cơ cấu dầm xoắn (torsion beam) và thanh cân bằng',1610, N'Hợp kim 17"', N'225/45R17', N'2225/45R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'11300000', N'340000', N'15600', N'837400', N'150000', N'14187400', N'k',6)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (55, N'2018 CHEVROLET COLORADO LT 2.5', CAST(N'2018-09-12 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Chevrolet/chev17.jpg;image/Chevrolet/chev18.jpg;image/Chevrolet/chev19.jpg;image/Chevrolet/chev20.jpg;image/Chevrolet/chev17.jpg;image/Chevrolet/chev18.jpg;image/Chevrolet/chev19.jpg;image/Chevrolet/chev20.jpg;',620, N'MS Thảo', N' 0934022388', N'38 Chế Lan Viên, P.Tây Thạnh, Q.Tân Phú, Tp Hồ Chí Minh', N'Pickup', N'Trắng', N'Nhập khẩu', 4, N'Xăng 2.5L ', 5, N'Sàn 5 cấp', 26000, N'', N'159 Hp@6,500 vòng/phút', N'194 Nm@4,800 vòng/phút', N'4WD', 58, N'5,347 x 1,882 x 1,821', 3096, 6.4, 216, N'Phụ thuộc, cơ cấu trục cố định',1510, N'Hợp kim 17"', N'225/45R17', N'2225/45R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'12980000', N'340000', N'15600', N'837400', N'150000', N'23406300', N'k',6)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (56, N'2016 CHEVROLET CAPTIVA REVV 2.4', CAST(N'2018-09-12 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Chevrolet/chev21.jpg;image/Chevrolet/chev22.jpg;image/Chevrolet/chev23.jpg;image/Chevrolet/chev24.jpg;image/Chevrolet/chev21.jpg;image/Chevrolet/chev22.jpg;image/Chevrolet/chev23.jpg;image/Chevrolet/chev24.jpg;',750, N'Lê Mạnh', N'010937238111 ', N'Quận 7, HCM, Quận 7, Tp Hồ Chí Minhh', N'SUV/Crossover', N'Trắng', N'NTrong nước', 5, N'Xăng 2.4L ', 7, N'Tự động 6 cấp', 33000, N'', N'159 Hp@6,500 vòng/phút', N'194 Nm@4,800 vòng/phút', N'2WD(Cầu trước)', 58, N'4,525 x 1,805 x 1,610', 2745, 2.2, 151, N'Thanh xoắn',1510, N'Hợp kim nhôm', N'225/45R17', N'2225/45R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'15600000', N'20700', N'15600', N'837400', N'150000', N'18487400', N'k',6)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (57, N'2018 CHEVROLET AVEO LT 1.5', CAST(N'2018-09-12 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Chevrolet/chev25.jpg;image/Chevrolet/chev26.jpg;image/Chevrolet/chev27.jpg;image/Chevrolet/chev28.jpg;image/Chevrolet/chev25.jpg;image/Chevrolet/chev26.jpg;image/Chevrolet/chev27.jpg;image/Chevrolet/chev28.jpg;',399, N'Lương Lưu Hoài Khanh', N'0965143488', N'38 Chế Lan Viên, Tân Phú, Tp Hồ Chí Minh', N'Sedan', N'Bạc', N'Nhập khẩu', 5, N'Xăng 2.0L ', 7, N'Tự động 6 cấp', 16000, N'', N'159 Hp@6,500 vòng/phút', N'194 Nm@4,800 vòng/phút', N'2WD(Cầu trước)', 58, N'4,525 x 1,805 x 1,610', 2745, 2.2, 151, N'Độc lập, cơ cấu đòn kéo (trailing arm) và thanh cân bằng',1510, N'Hợp kim nhôm', N'225/45R17', N'2225/45R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'39900000', N'340000', N'15600', N'837400', N'150000', N'54236700', N'k',6)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (58, N'2016 CHEVROLET CRUZE LT', CAST(N'2018-09-12 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Chevrolet/chev29.jpg;image/Chevrolet/chev30.jpg;image/Chevrolet/chev31.jpg;image/Chevrolet/chev32.jpg;image/Chevrolet/chev29.jpg;image/Chevrolet/chev30.jpg;image/Chevrolet/chev31.jpg;image/Chevrolet/chev30.jpg;',455, N'Võ Văn Mến', N' 01639503339 ', N'Ford An Lạc, Bình Tân, Tp Hồ Chí Minh', N'Wagon/Van/ Minivan/MPV', N'Vàng', N'Nhập khẩu', 5, N'Xăng 2.0L ', 7, N'Tự động 6 cấp', 17000, N'', N'159 Hp@6,500 vòng/phút', N'194 Nm@4,800 vòng/phút', N'2WD(Cầu trước)', 58, N'4,525 x 1,805 x 1,610', 2745, 2.2, 151, N'Thanh xoắn',1510, N'Hợp kim nhôm', N'225/45R17', N'2225/45R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'9100000', N'340000', N'15600', N'837400', N'150000', N'12000000', N'k',6)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (59, N'2008 CHEVROLET VIVANT CDX 2.0 AT', CAST(N'2018-09-12 00:00:00.000' AS DateTime), N'Tp Hà Nội', N'image/Chevrolet/chev33.jpg;image/Chevrolet/chev34.jpg;image/Chevrolet/chev35.jpg;image/Chevrolet/chev36.jpg;image/Chevrolet/chev33.jpg;image/Chevrolet/chev34.jpg;image/Chevrolet/chev35.jpg;image/Chevrolet/chev36.jpg;',185, N'Phạm Ngọc Ánh', N' 01639503339 ', N'Ngõ An sơn Đại La, Quận Hai Bà Trưng, Tp Hà Nộ', N'SUV/Crossover', N'Vàng', N'Nhập khẩu', 5, N'Xăng 2.0L ', 7, N'Tự động 6 cấp', 16000, N'', N'159 Hp@6,500 vòng/phút', N'194 Nm@4,800 vòng/phút', N'2WD(Cầu trước)', 58, N'4,525 x 1,805 x 1,610', 2745, 2.2, 151, N'Thanh xoắn',1510, N'Hợp kim nhôm', N'225/45R17', N'2225/45R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'3700000', N'340000', N'15600', N'837400', N'150000', N'6587400', N'k',6)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (60, N'2010 CHEVROLET CAPTIVA MAXX LT 2.4', CAST(N'2018-09-12 00:00:00.000' AS DateTime),N'Tp Hồ Chí Minh', N'image/Chevrolet/chev1.jpg;image/Chevrolet/chev2.jpg;image/Chevrolet/chev3.jpg;image/Chevrolet/chev4.jpg;image/Chevrolet/chev1.jpg;image/Chevrolet/chev2.jpg;image/Chevrolet/chev3.jpg;image/Chevrolet/chev4.jpg;',620, N'PHÚ LÂM AUTO', N' 01639503339 ', N'464 Kinh Dương Vương, Bình Tân, Tp Hồ Chí Minh', N'Wagon/Van/ Minivan/MPV', N'Xám', N'Nhập khẩu', 5, N'Xăng 2.0L ', 7, N'Tự động 6 cấp', 16000, N'', N'159 Hp@6,500 vòng/phút', N'194 Nm@4,800 vòng/phút', N'2WD(Cầu trước)', 58, N'4,525 x 1,805 x 1,610', 2745, 2.2, 151, N'Bán độc lập, cơ cấu dầm xoắn (torsion beam) và thanh cân bằng',1510, N'Hợp kim nhôm', N'225/45R17', N'2225/45R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'k', N'9000000', N'340000', N'15600', N'837400', N'150000', N'12486700', N'k',6)

/*Hang 9*/
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (21, N'2018 MERCEDES-BENZ GLC-CLASS GLC200', CAST(N'2018-09-17 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Mercedes/2018-Mercedes-Benz-GLC-Class(1).jpg;image/Mercedes/2018-Mercedes-Benz-GLC-Class(2).jpg;image/Mercedes/2018-Mercedes-Benz-GLC-Class(3).jpg;image/Mercedes/2018-Mercedes-Benz-GLC-Class(4).jpg;image/Mercedes/2018-Mercedes-Benz-GLC-Class(5).jpg;image/Mercedes/2018-Mercedes-Benz-GLC-Class(6).jpg;image/Mercedes/2018-Mercedes-Benz-GLC-Class(7).jpg;image/Mercedes/2018-Mercedes-Benz-GLC-Class(8).jpg;', 1684, N'Nguyễn Đăng Minh Phương', N'0966210210  ', N'811-813 Nguyễn Văn Linh, Tân Phú, Quận 7, Hồ Chí Minh, Quận 7, Tp Hồ Chí Minh', N'SUV/Crossover', N'Trắng', N'Trong nước', 4, N'Xăng 2.0L', 5, N'Tự động 7 cấp', 350, N'', N'148 Hp @3,400 vòng/phút', N'400 Nm @1,600-2,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2745, 58, 219, N'Phụ thuộc, liên kết 4 điểm', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'33680000', N'340000', N'1560000', N'1436700', N'150000', N'37166700', N'', 9)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (22, N'2017 MERCEDES-BENZ E-CLASS', CAST(N'2018-09-13 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Mercedes/2017-Mercedes-Benz-E-Class-E250(1).jpg;image/Mercedes/2017-Mercedes-Benz-E-Class-E250(2).jpg;image/Mercedes/2017-Mercedes-Benz-E-Class-E250(3).jpg;image/Mercedes/2017-Mercedes-Benz-E-Class-E250(4).jpg;image/Mercedes/2017-Mercedes-Benz-E-Class-E250(5).jpg;image/Mercedes/2017-Mercedes-Benz-E-Class-E250(6).jpg;image/Mercedes/2017-Mercedes-Benz-E-Class-E250(7).jpg;image/Mercedes/2017-Mercedes-Benz-E-Class-E250(8).jpg;', 2479, N'Nguyễn Đăng Minh Phương', N'0966210210  ', N'811-813 Nguyễn Văn Linh, Tân Phú, Quận 7, Hồ Chí Minh, Quận 7, Tp Hồ Chí Minh', N'Sedan', N'Đen', N'Trong nước', 4, N'Xăng 2.0L', 5, N'Tự động 9 cấp', 101, N'', N'148 Hp @3,400 vòng/phút', N'400 Nm @1,600-2,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2745, 58, 219, N'Phụ thuộc, liên kết 4 điểm', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'49580000', N'340000', N'1560000', N'1436700', N'150000', N'53066700', N'', 9)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (23, N'2017 MERCEDES-BENZ C-CLASS 200', CAST(N'2018-09-11 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Mercedes/2017-Mercedes-Benz-C-Class-200(1).jpg;image/Mercedes/2017-Mercedes-Benz-C-Class-200(2).jpg;image/Mercedes/2017-Mercedes-Benz-C-Class-200(3).jpg;image/Mercedes/2017-Mercedes-Benz-C-Class-200(4).jpg;image/Mercedes/2017-Mercedes-Benz-C-Class-200(5).jpg;image/Mercedes/2017-Mercedes-Benz-C-Class-200(6).jpg;image/Mercedes/2017-Mercedes-Benz-C-Class-200(7).jpg;image/Mercedes/2017-Mercedes-Benz-C-Class-200(8).jpg;', 1469, N'Nguyễn Đăng Minh Phương', N'0966210210  ', N'811-813 Nguyễn Văn Linh, Tân Phú, Quận 7, Hồ Chí Minh, Quận 7, Tp Hồ Chí Minh', N'Sedan', N'Nâu', N'Trong nước', 4, N'Xăng 2.0L', 5, N'Tự động 9 cấp', 101, N'', N'137 Hp @5,600 vòng/phút', N'183 Nm @4,000 vòng/phút', N'2WD(Cầu sau)', 70, N'4,735 x 1,830 x 1,795', 2745, 54, 178, N'Liên kết 4 điểm, lò xo cuộn và tay đòn bên', 1700, N'Hợp kim 16"', N'265/65R17', N'205/65R16', N'Đĩa', N'Tang trống', 7.8, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'29380000', N'340000', N'1560000', N'1436700', N'150000', N'32866700', N'', 9)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (24, N'2017 MERCEDES-BENZ S-CLASS S450L', CAST(N'2018-09-08 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Mercedes/2017-Mercedes-Benz-S-Class-S450L(1).jpg;image/Mercedes/2017-Mercedes-Benz-S-Class-S450L(2).jpg;image/Mercedes/2017-Mercedes-Benz-S-Class-S450L(3).jpg;image/Mercedes/2017-Mercedes-Benz-S-Class-S450L(4).jpg;image/Mercedes/2017-Mercedes-Benz-S-Class-S450L(5).jpg;', 4100, N'Nguyễn Đăng Minh Phương', N'0966210210  ', N'811-813 Nguyễn Văn Linh, Tân Phú, Quận 7, Hồ Chí Minh, Quận 7, Tp Hồ Chí Minh', N'Sedan', N'Đen', N'Trong nước', 4, N'Xăng 4.5L', 5, N'Tự động 9 cấp', 3500, N'', N'142 Hp @3,400 vòng/phút', N'343 Nm @1,600-2,800 vòng/phút', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2750, 59, 220, N'Phụ thuộc, cơ cấu trục cố định liên kết đa điểm và thanh cân bằng', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 7.8, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'82000000', N'340000', N'1560000', N'1436700', N'150000', N'85486700', N'', 9)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (25, N'2016 MERCEDES-BENZ A-CLASS 250 AMG', CAST(N'2018-07-17 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Mercedes/2016-Mercedes-Benz-A-Class-250-AMG(1).jpg;image/Mercedes/2016-Mercedes-Benz-A-Class-250-AMG(2).jpg;image/Mercedes/2016-Mercedes-Benz-A-Class-250-AMG(3).jpg;image/Mercedes/2016-Mercedes-Benz-A-Class-250-AMG(4).jpg;image/Mercedes/2016-Mercedes-Benz-A-Class-250-AMG(5).jpg;image/Mercedes/2016-Mercedes-Benz-A-Class-250-AMG(6).jpg;image/Mercedes/2016-Mercedes-Benz-A-Class-250-AMG(7).jpg;image/Mercedes/2016-Mercedes-Benz-A-Class-250-AMG(8).jpg;', 1659, N'Nguyễn Đăng Minh Phương', N'0966210210  ', N'811-813 Nguyễn Văn Linh, Tân Phú, Quận 7, Hồ Chí Minh, Quận 7, Tp Hồ Chí Minh', N'Hatchback', N'Đỏ', N'Nhập khẩu', 5, N'Xăng 2.0L', 5, N'Tự động 7 cấp', 35000, N'', N'158 Hp @5,200 vòng/phút', N'241 Nm @3,800 vòng/phút', N'2WD(Cầu sau)', 80, N'4,705 x 1,840 x 1,850', 2750, 59, 220, N'Phụ thuộc, cơ cấu trục cố định liên kết đa điểm và thanh cân bằng', 1770, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'33180000', N'340000', N'1560000', N'1436700', N'150000', N'36666700', N'', 9)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (26, N'2015 MERCEDES-BENZ GLE-CLASS 400 4MATIC', CAST(N'2018-08-31 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Mercedes/2015-Mercedes-Benz-GLE-Class-400-4MATIC(1).jpg;image/Mercedes/2015-Mercedes-Benz-GLE-Class-400-4MATIC(2).jpg;image/Mercedes/2015-Mercedes-Benz-GLE-Class-400-4MATIC(3).jpg;image/Mercedes/2015-Mercedes-Benz-GLE-Class-400-4MATIC(4).jpg;image/Mercedes/2015-Mercedes-Benz-GLE-Class-400-4MATIC(5).jpg;image/Mercedes/2015-Mercedes-Benz-GLE-Class-400-4MATIC(6).jpg;', 3050, N'Anh Tân', N'0934043933  ', N'175/4 Nguyễn Kiệm, Phú Nhuận, Phú Nhuận, Tp Hồ Chí Minh', N'Coupe', N'Trắng', N'Nhập khẩu', 5, N'Xăng 3.0L', 7, N'Tự động 9 cấp', 40000, N'', N'142 Hp @3,400 vòng/phút', N'343 Nm @1,600-2,800 vòng/phút', N'2WD(Cầu sau)', 80, N'4,705 x 1,840 x 1,850', 2750, 59, 220, N'Phụ thuộc, cơ cấu trục cố định liên kết đa điểm và thanh cân bằng', 1820, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'61000000', N'340000', N'1560000', N'1436700', N'150000', N'64486700', N'', 9)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (27, N'2018 MERCEDES-BENZ C-CLASS 200', CAST(N'2018-08-17 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Mercedes/2018-Mercedes-Benz-C-Class-200(1).jpg;image/Mercedes/2018-Mercedes-Benz-C-Class-200(2).jpg;image/Mercedes/2018-Mercedes-Benz-C-Class-200(3).jpg;image/Mercedes/2018-Mercedes-Benz-C-Class-200(4).jpg;image/Mercedes/2018-Mercedes-Benz-C-Class-200(5).jpg;image/Mercedes/2018-Mercedes-Benz-C-Class-200(6).jpg;image/Mercedes/2018-Mercedes-Benz-C-Class-200(7).jpg;', 1320, N'TT Mercedes Cũ Chính Hãng', N'0977777072  ', N'02 Trường Trinh, Tân Phú, Tp Hồ Chí Minh', N'Sedan', N'Đen', N'Trong nước', 4, N'Xăng 2.0L', 5, N'Tự động 9 cấp', 10000, N'', N'138 Hp @6,400 vòng/phút', N'173 Nm @4,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,620 x 1,775 x 1,460', 2700, 54, 130, N'Bán độc lập, cơ cấu dầm xoắn (torsion beam) và thanh cân bằng', 1260, N'Hợp kim 16"', N'205/55R16', N'265/65R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'26400000', N'340000', N'1560000', N'1436700', N'150000', N'29886700', N'', 9)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (28, N'2017 MERCEDES-BENZ C-CLASS 250 EXCLUSIVE', CAST(N'2018-08-07 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Mercedes/2017-Mercedes-Benz-C-Class-250-Exclusive(1).jpg;image/Mercedes/2017-Mercedes-Benz-C-Class-250-Exclusive(2).jpg;image/Mercedes/2017-Mercedes-Benz-C-Class-250-Exclusive(3).jpg;image/Mercedes/2017-Mercedes-Benz-C-Class-250-Exclusive(4).jpg;image/Mercedes/2017-Mercedes-Benz-C-Class-250-Exclusive(5).jpg;image/Mercedes/2017-Mercedes-Benz-C-Class-250-Exclusive(6).jpg;image/Mercedes/2017-Mercedes-Benz-C-Class-250-Exclusive(7).jpg;image/Mercedes/2017-Mercedes-Benz-C-Class-250-Exclusive(8).jpg;', 1729, N'Nguyễn Đăng Minh Phương', N'0966210210  ', N'811-813 Nguyễn Văn Linh, Tân Phú, Quận 7, Hồ Chí Minh, Quận 7, Tp Hồ Chí Minh', N'Sedan', N'Xanh dương', N'Trong nước', 4, N'Xăng 2.0L', 5, N'Tự động 9 cấp', 3500, N'', N'148 Hp @3,400 vòng/phút', N'400 Nm @1,600-2,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,795 x 1,855 x 1,835', 2745, 58, 219, N'Phụ thuộc, liên kết 4 điểm', 1990, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'34580000', N'340000', N'1560000', N'1436700', N'150000', N'38066700', N'', 9)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (29, N'2016 MERCEDES-BENZ S-CLASS 500L', CAST(N'2018-07-24 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Mercedes/2016-Mercedes-Benz-S-Class-500L(1).jpg;image/Mercedes/2016-Mercedes-Benz-S-Class-500L(2).jpg;image/Mercedes/2016-Mercedes-Benz-S-Class-500L(3).jpg;image/Mercedes/2016-Mercedes-Benz-S-Class-500L(4).jpg;image/Mercedes/2016-Mercedes-Benz-S-Class-500L(5).jpg;image/Mercedes/2016-Mercedes-Benz-S-Class-500L(6).jpg;image/Mercedes/2016-Mercedes-Benz-S-Class-500L(7).jpg;image/Mercedes/2016-Mercedes-Benz-S-Class-500L(8).jpg;', 5750, N'Nguyễn Đăng Minh Phương', N'0966210210  ', N'811-813 Nguyễn Văn Linh, Tân Phú, Quận 7, Hồ Chí Minh, Quận 7, Tp Hồ Chí Minh', N'Sedan', N'Đen', N'Trong nước', 4, N'Xăng 5.0L', 7, N'Tự động 9 cấp', 6800, N'', N'158 Hp @5,200 vòng/phút', N'241 Nm @3,800 vòng/phút', N'2WD(Cầu sau)', 80, N'4,705 x 1,840 x 1,850', 2750, 59, 220, N'Phụ thuộc, cơ cấu trục cố định liên kết đa điểm và thanh cân bằng', 1770, N'Hợp kim 17"', N'265/65R17', N'265/65R17', N'Đĩa', N'Đĩa', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'115000000', N'340000', N'1560000', N'1436700', N'150000', N'118486700', N'', 9)
INSERT [dbo].[Xe] ([ID_Xe], [TenXe], [NgayDang], [KhuVuc], [Anh], [Gia], [TenChuXe], [SDT], [DiaChi], [KieuDang], [MauSac], [XuatXu], [SoCua], [NhienLieu], [SoCho], [LoaiHopSo], [SoKm], [GioiThieu], [CongXuat], [MomemXoan], [TruyenDong], [DungTich], [KichThuoc_DxRxC_], [ChieuDaiCoSo], [BanKinhQuayDau], [KhoangSangGam], [HeThongTreoSau], [TrongLuongKhongTai], [Mam_Vanh], [KichThuocLopTruoc], [KichThuocLopSau], [PhanhTruoc], [PhanhSau], [TieuThuNhienLieu], [TangAp], [DieuHoa], [CuaSoTroi], [DVD_LCD], [JackCamLoa], [LopSo-Cua], [TuiKhi], [Cameralui], [CamBienLui], [ChongBoCungPhanh], [PhanBoLucPhanhDienTu], [TroLucPhanhKhanCap], [HeThongHoTroKhoiDong], [NoiDangKy], [PhiTruocBa], [PhiDangKiem], [PhiDuongBo], [BaoHiemDanSu], [PhiSangTen], [TongPhi], [BanDo], [ID_Hang]) VALUES (30, N'2018 MERCEDES-BENZ CLA-CLASS 45', CAST(N'2018-07-15 00:00:00.000' AS DateTime), N'Tp Hồ Chí Minh', N'image/Mercedes/2018-Mercedes-Benz-CLA-Class-45(1).jpg;image/Mercedes/2018-Mercedes-Benz-CLA-Class-45(2).jpg;image/Mercedes/2018-Mercedes-Benz-CLA-Class-45(3).jpg;image/Mercedes/2018-Mercedes-Benz-CLA-Class-45(4).jpg;image/Mercedes/2018-Mercedes-Benz-CLA-Class-45(5).jpg;image/Mercedes/2018-Mercedes-Benz-CLA-Class-45(6).jpg;image/Mercedes/2018-Mercedes-Benz-CLA-Class-45(7).jpg;', 2250, N'TT Mercedes Cũ Chính Hãng', N'0977777072  ', N'02 Trường Trinh, Tân Phú, Tp Hồ Chí Minh', N'Sedan', N'Trắng', N'Nhập khẩu', 4, N'Xăng 2.0L', 5, N'Tự động 7 cấp', 1000, N'', N'134 Hp @5,600 vòng/phút', N'182 Nm @4,000 vòng/phút', N'2WD(Cầu sau)', 80, N'4,589 x 1,775 x 1,750', 2750, 54, 176, N'Phụ thuộc, cơ cấu trục cố định liên kết đa điểm và thanh cân bằng', 1605, N'Hợp kim 15"', N'205/65R15', N'205/65R15', N'Đĩa', N'Tang trống', 6.2, N'Không', N'Có', N'Có', N'Có', N'Có', N'Có', N'2 túi khí', N'Có', N'Có', N'Có', N'Có', N'Có', N'Có', N'', N'45000000', N'340000', N'1560000', N'1436700', N'150000', N'48486700', N'', 9)


SET IDENTITY_INSERT [dbo].[Xe] OFF
Alter table [Xe] add  foreign key([ID_Hang]) references [HangXe] ([ID_Hang])  on update no action on delete no action 
go
Alter table [DonHang] add  foreign key([ID_Xe]) references [Xe] ([ID_Xe])  on update no action on delete no action 
go
Alter table [DonHang] add  foreign key([ID_TK]) references [TaiKhoan] ([ID_TK])  on update no action on delete no action 
go

Set quoted_identifier on
go


Set quoted_identifier off
go


